- README.md
> s21015 アニメ追加

- README.md
> s21011 アニメ追加

- README.md
> s21002 アニメ追加

- README.md
> s21018 アニメ追加

- README.md
> 学籍番号　アニメ追加

- README.md
> s21012 アニメ追加

- README.md
> 学籍番号 アニメ追加

- README.md
> 学籍番号　アニメを追加

- README.md
> 学籍番号 anime

- README.md
> s21019アニメ追加

- README.md
> s22024 アニメ追加

- README.md
> s22004 ドリフターズ

- README.md
> s22017 アニメ追加

- README.md
> s22026 暗殺教室

- README.md
> s22022アニメ追加

- README.md
s22025 半嶺 凜のプルリクエストです。
よろしくお願いします。
> s22025 アニメ追加

- README.md
> s22021 アニメ追加

- README.md
> s22001 アニメ追加

- README.md
> s22012 アニメ追加

- README.md
> S22007 anime

- README.md
> s22008 アニメ追加

- README.md
> s22019 アニメ追加

- README.md
> s22030 アニメ追加

- README.md
> S22029 anime

- README.md
> S22016 anime
